APM-261686 Publish S205 dashboards
Dynatrace/snippets pull request #29
Opened 2020-10-20 12:40 UTC by dt-be

AWS MediaPackage VOD - public since 204
AWS Billing - public since 204
Azure App Deployment Slots - public since 203  - new Function App dashboard next to the existing dashboard for Web App version

@wojtasskorcz @Dawid-Kaszubski please check
@danielkhan @alramlechner

2020-10-20 12:47 UTC, wojtasskorcz requested changes

2020-10-20 12:47 UTC, wojtasskorcz commented on product/dashboarding/aws-supporting-services/Billing.json
> +                            "CUSTOM_DEVICE-941EBB5DFAA4841F"
remove this and other CD-specific filters

2020-10-20 12:47 UTC, wojtasskorcz commented on product/dashboarding/azure-supporting-services/AppServiceFunctionDeploymentSlots.json
> +    "metadata": {
Remove `metadata` and `id`

2020-10-20 12:47 UTC, wojtasskorcz commented on product/dashboarding/aws-supporting-services/Billing.json
> +        "owner": "Dynatrace"
IIRC `owner` was supposed to be removed too

2020-10-20 12:47 UTC, wojtasskorcz commented on product/dashboarding/azure-supporting-services/README.MD
>  ### [Azure App Service Deployment Slots](AppServiceDeploymentSlots.json)
Maybe let's rename it to `AppServiceWebDeploymentSlots`? Not a big issue though

2020-10-20 12:52 UTC, dt-be commented on product/dashboarding/azure-supporting-services/AppServiceFunctionDeploymentSlots.json
> +    "metadata": {
it seemed inconsistent in other dashboards, especially as I saw configurationVersions 2 and 3 and thought it might be relevant.

2020-10-20 13:09 UTC, wojtasskorcz commented on product/dashboarding/azure-supporting-services/AppServiceFunctionDeploymentSlots.json
> +    "metadata": {
Alright, I'm not entirely sure about `metadata`. It's just something that I was told to do in my previous PR

2020-10-20 13:10 UTC, wojtasskorcz approved these changes

2020-10-20 15:20 UTC, Dawid-Kaszubski approved these changes

2020-10-20 15:24 UTC, dt-be commented
@danielkhan @alramlechner passing on to you for review or merge

2020-10-21 07:20 UTC, dt-be commented
Marysia requested changes to Billing.

2020-10-21 11:41 UTC, wojtasskorcz approved these changes

2020-10-22 07:31 UTC, danielkhan approved these changes

2020-10-22 11:00 UTC, merged